name = "gloat"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "A type checker for gleam, written in gleam! Mostly serving as a learning tool, demonstrating how type checkers work."
licences = ["Apache-2.0"]
repository = { type = "github", user = "jaredly", repo = "gloat" }
#
# For a full reference of all the available options, you can have a look at
# pubgrub = {git = "https://github.com/jaredly/pubgrub.git", ref = "a1ea943"}
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glance = ">= 6.0.0 and < 7.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
glexer = ">= 2.3.1 and < 3.0.0"
pubgrub = {path= "../../fork/pubgrub"}

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[executable]
name = "gloat"
module = "gloat_cli"
